version: "3.8"

services:

  tomcat:
   image: techforum/tomcat-extended:latest
   container_name: tomcat
   
   environment:
     CATALINA_OPTS: "-javaagent:/usr/local/tomcat/lib/jacocoagent.jar=port=6300,address=0.0.0.0,destfile=/tmp/jacoco-remote.exec,includes=com.sample.*,append=true,output=tcpserver"

   ports:
     - 8080:8080
     - 6300:6300

   volumes:
     - ./helloword-host-mounted.war:/usr/local/tomcat/webapps/helloword-host-mounted.war
     - ./code-coverage-remote.war:/usr/local/tomcat/webapps/code-coverage-remote.war
